[package]
name = "myls"
version = "0.1.2"
authors = ["lome <1209518758@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
term_size = "0.3.0"